### PR TITLE
[MYEN-545] add accepted roles check

### PR DESCRIPTION
**Pull request by dwojno**

### CODE REVIEW

**Review by jrhender — CHANGES_REQUESTED** [review]
Nice work, I like the general approach 👍  However, please see PR #25 with my suggested changes and merge into this PR's branch if you approve, as I think there is a regression where null values are being included in returned claims.

**Comment by dwojno** [comment]
@jrhender I think it will be easier to just fix the issue here, without merging branches :)

**Review by jrhender — APPROVED** [review]

**Pull request merged**
