### PR TITLE
feat(LoginStrategy): add cacheServerVersion param

### PR DESCRIPTION
**Pull request by jrhender**
This param is append to the end of the cacheServerUrl if present.

### CODE REVIEW

**Review by ahmedolaibrahim — APPROVED** [review]
Looks good to me..

**Comment by jrhender** [comment]
@ahmedolaibrahim I'm a bit confused why this would be necessary actually. It seems one could accomplish the same thing with the current version of `passpor-did-auth` by simply passing in the full URL. E.g. instead of using `cacheServerUrl: https://identitycache-dev.energyweb.org/`, use `cacheServerUrl: https://identitycache-dev.energyweb.org/v1/`

**Review by JGiter — APPROVED** [review]
Have you tried if this works? I tried this way by appending `v1` to cacheServerUrl in `AuthStrategy` constructor on cache server but had 401

**Comment by ahmedolaibrahim** [comment]
> @ahmedolaibrahim I'm a bit confused why this would be necessary actually. It seems one could accomplish the same thing with the current version of `passpor-did-auth` by simply passing in the full URL. E.g. instead of using `cacheServerUrl: https://identitycache-dev.energyweb.org/`, use `cacheServerUrl: https://identitycache-dev.energyweb.org/v1/`

@jrhender my argument against adding versions as part of the base URL is that a user of this library might want to use v1 for some routes on the cache server and maybe another version e.g `/v2` depending on their needs. adding it as part of a base URL defeats that purpose.

**Comment by jrhender** [comment]
Closing as not necessary to accomplish https://github.com/energywebfoundation/iam-cache-server/pull/162

**Pull request closed without merging**
