### PR TITLE
Chore/ew did registry deps

### PR DESCRIPTION
**Pull request by jrhender**
For more information see PR #39 . I merged that PR into chore/ew-did-registry-deps branch on this repository so that Travis would pick it up and build to allow merge into develop (which requires successful Travis build).

### CODE REVIEW

**Comment by jrhender** [comment]
@kosecki123 Is it necessary to delete the `package-lock.json` file for `yarn/pnpm` to work?

**Comment by kosecki123** [comment]
> @kosecki123 Is it necessary to delete the `package-lock.json` file for `yarn/pnpm` to work?

Nope. Lock files are for development purposes only.

**Comment by jrhender** [comment]
> > @kosecki123 Is it necessary to delete the `package-lock.json` file for `yarn/pnpm` to work?
> 
> Nope. Lock files are for development purposes only.

Interesting. I always thought that the package-lock.json was useful so that changes to the installed versions could be more easily diffed and compared between developers, but I guess there is a downside to having it for libraries because it can't be published to npm so having it makes it less likely that bugs experienced by users will be caught. Is that why you recommend not having it in source control?

**Comment by jrhender** [comment]
> > @kosecki123 Is it necessary to delete the `package-lock.json` file for `yarn/pnpm` to work?
> 
> Nope. Lock files are for development purposes only.

@kosecki123 Just to clarify, if it isn't necessary to delete the `package-lock.json`, did you intend for your commit to do so?

**Comment by kosecki123** [comment]
> > > @kosecki123 Is it necessary to delete the `package-lock.json` file for `yarn/pnpm` to work?
> 
> > 
> 
> > Nope. Lock files are for development purposes only.
> 
> 
> 
> @kosecki123 Just to clarify, if it isn't necessary to delete the `package-lock.json`, did you intend for your commit to do so?

OMG, deleting lock file is a mistake. 

Not sure why I haven't check that sorry.

**Comment by jrhender** [comment]
Sorry, my fault. Everything goods fine. I got confused by the github diff UI and thought the package-lock.json was deleted but it's still there. 🤦

**Review by dwojno — APPROVED** [review]

**Pull request merged**
