### PR TITLE
docs: update docs with new LoginStrategy options

### PR DESCRIPTION
**Pull request by jrhender**
LoginStrategy checks optional list of approvedRoles.
Changes made in previous commits.
This commit is just updating documentation and triggering semantic release.

@JGiter Is this commit in the correct format to trigger automated semantic-release deployment to npm?

### CODE REVIEW

**Review by dwojno — APPROVED** [review]

**Comment by JGiter** [comment]
> LoginStrategy checks optional list of approvedRoles.
> Changes made in previous commits.
> This commit is just updating documentation and triggering semantic release.
> 
> @JGiter Is this commit in the correct format to trigger automated semantic-release deployment to npm?

@jrhender Yes, commit format is correct

**Review by JGiter — APPROVED** [review]

**Comment by jrhender** [comment]
As PR #27 pushed the AcceptedRoles change to npm, I changed this PR to just be docs update

**Pull request merged**
